# Generated by Django 4.1.13 on 2025-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=100)),
                ("receiver_phone", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("detail_address", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
    ]
