# Generated by Django 5.1.5 on 2025-03-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_address_consumer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="consumer_id",
            new_name="consumer",
        ),
    ]
