# Generated by Django 4.1.13 on 2025-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
            ],
        ),
    ]
