# Generated by Django 4.1.13 on 2025-03-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="images",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
