# Generated by Django 5.1.5 on 2025-03-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(default="default.png", max_length=50),
        ),
    ]
