# Generated by Django 2.1.5 on 2025-03-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_id_alter_userprofile_user_type'),
        ('users', '0002_auto_20250318_1518'),
    ]

    operations = [
    ]
