# Generated by Django 5.1.5 on 2025-03-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_product_image_cartitem_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product_id_test",
            field=models.IntegerField(default=0),
        ),
    ]
