# Generated by Django 5.1.5 on 2025-03-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_product_id_test"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_product_variant_in_cart",
        ),
    ]
