# Generated by Django 5.1.5 on 2025-03-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cartitem_unique_product_variant_in_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
    ]
