# Generated by Django 5.1.5 on 2025-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("paypal", "PayPal"),
                    ("wechat", "WeChat Pay"),
                    ("alipay", "Alipay"),
                    ("cash", "Cash on Delivery"),
                ],
                default="credit_card",
                max_length=20,
            ),
        ),
    ]
