# Generated by Django 5.1.5 on 2025-03-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
    ]
