# Generated by Django 5.1.5 on 2025-03-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_product_delete_order_item_payment_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0)),
                ("quantity", models.FloatField(default=0)),
                ("unit_price", models.FloatField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.product",
                    ),
                ),
            ],
        ),
    ]
