# Generated by Django 5.1.5 on 2025-03-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="Order",
            new_name="order",
        ),
    ]
