# Generated by Django 5.1.5 on 2025-03-17 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_order_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_item",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
