# Generated by Django 5.1.5 on 2025-03-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_item_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid_state",
            new_name="paid_status",
        ),
    ]
