# Generated by Django 5.1.5 on 2025-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_rename_paid_state_payment_paid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="merchant",
            name="shop_description",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
