# Generated by Django 5.1.5 on 2025-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_merchant_email_merchant_shop_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
