# Generated by Django 5.1.2 on 2025-03-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_rename_consumer_id_address_consumer'),
        ('orders', '0009_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
