# Generated by Django 5.1.2 on 2025-03-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_description_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_state',
            new_name='order_status',
        ),
    ]
