# Generated by Django 5.1.5 on 2025-03-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productattribute_productattributevalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
